name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 16.12.0 # renovate: node

      - name: Release
        run: npx semantic-release -b main -p @semantic-release/commit-analyzer,@semantic-release/release-notes-generator,@semantic-release/github --debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Bump version and push tag
      #   id: tag
      #   uses: mathieudutour/github-tag-action@v5.6
      #   with:
      #     default_bump: false
      #     github_token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Generate metadata
      #   id: metadata
      #   uses: docker/metadata-action@v3.6.0
      #   if: steps.tag.outputs.new_tag
      #   with:
      #     images: ghcr.io/${{ github.repository_owner }}/pytest
      #     tags: |
      #       type=raw,value=${{ steps.tag.outputs.new_version }}
      #     flavor: |
      #       latest=true

      - name: Login to registry
        uses: docker/login-action@v1.10.0
        if: steps.tag.outputs.new_tag
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2.7.0
        if: steps.tag.outputs.new_tag
        with:
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}

      # - name: Create a GitHub release
      #   uses: ncipollo/release-action@v1
      #   if: steps.tag.outputs.new_tag
      #   with:
      #     tag: ${{ steps.tag.outputs.new_tag }}
      #     body: ${{ steps.tag.outputs.changelog }}
