name: Renovate

on:
  schedule:
    - cron: '0/5 * * * *'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0

      - name: Renovate
        uses: renovatebot/github-action@v27.31.10
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
